"""Pinned model metadata from LiteLLM's bundled cost map, read without LiteLLM.

Telemetry needs to know whether a model id is a public SKU, and the savings
helpers need per-token list prices. Both used to import the LiteLLM SDK on the
response-finalization path: ~1.6s, plus an import-time fetch of its remote price
map. This module instead reads a Headroom-owned copy of the map bundled in the
exact LiteLLM wheel pinned by ``uv.lock``, generated by
``scripts/generate_model_catalog.py``. The manifest beside the data records the
source wheel, hashes and license.

Pinned prices are reproducible, not current: refreshing them is a dependency
update plus regeneration, never a runtime fetch. General cost estimation
(``litellm_pricing``, ``proxy/cost.py``) still uses the SDK.
"""

from __future__ import annotations

import hashlib
import json
import logging
import math
import re
import threading
from collections.abc import Mapping
from dataclasses import dataclass
from pathlib import Path
from types import MappingProxyType
from typing import Any

logger = logging.getLogger(__name__)

SCHEMA_VERSION = 1
DATA_DIR = Path(__file__).parent / "data"
CATALOG_FILE = "litellm_model_catalog.json"
MANIFEST_FILE = "litellm_model_catalog.manifest.json"
# The pinned catalog is ~0.85 MB; LiteLLM's entire source map is 2.3 MB. The
# bound leaves room for upstream growth across refreshes while refusing to read
# an arbitrarily large replacement.
MAX_CATALOG_BYTES = 4 * 1024 * 1024
MAX_MANIFEST_BYTES = 64 * 1024

# Entries in LiteLLM's file that document its schema; they are not model ids.
RESERVED_KEYS = frozenset({"sample_spec", "fallback_generalizations"})

# Per-token list prices, including the context-length and cache-duration tiers
# no current caller reads. Service tiers (priority/flex/batch) and non-token
# units are out of scope.
_RATE_FIELD = re.compile(
    r"(input_cost_per_token|output_cost_per_token|input_cost_per_token_cache_hit"
    r"|cache_read_input_token_cost|cache_creation_input_token_cost"
    r"|cache_creation_input_token_cost_above_1hr)(_above_\d+k_tokens)?"
)
TEXT_FIELDS = frozenset({"litellm_provider", "mode"})
LIMIT_FIELDS = frozenset({"max_tokens", "max_input_tokens", "max_output_tokens"})


class CatalogError(ValueError):
    """Catalog data failed validation. The message is a fixed reason, never input text."""


@dataclass(frozen=True, slots=True)
class ModelCatalog:
    """Immutable, validated snapshot of the pinned catalog."""

    models: Mapping[str, Mapping[str, Any]]
    # Telemetry may emit exactly these ids. Pricing aliases never extend it.
    public_models: frozenset[str]
    # Keys the pinned SDK's ``cost_per_token`` probe rejects. The savings
    # resolver used that probe to choose among candidate names, so it skips them.
    unresolvable: frozenset[str]
    litellm_version: str

    def is_resolvable(self, name: str) -> bool:
        return name in self.models and name not in self.unresolvable


def is_catalog_field(name: str) -> bool:
    return name in TEXT_FIELDS or name in LIMIT_FIELDS or _RATE_FIELD.fullmatch(name) is not None


def is_valid_value(field: str, value: Any) -> bool:
    """Whether ``value`` is acceptable for a catalog field. Booleans are not numbers."""
    if field in TEXT_FIELDS:
        return isinstance(value, str)
    if field in LIMIT_FIELDS or _RATE_FIELD.fullmatch(field):
        return (
            isinstance(value, (int, float))
            and not isinstance(value, bool)
            and math.isfinite(value)
            and value >= 0
        )
    return False


def encode_catalog(value: Any) -> bytes:
    """Canonical UTF-8 JSON: sorted keys, no whitespace, no NaN, trailing newline."""
    text = json.dumps(
        value, sort_keys=True, ensure_ascii=False, separators=(",", ":"), allow_nan=False
    )
    return (text + "\n").encode("utf-8")


def parse_catalog(catalog_bytes: bytes, manifest_bytes: bytes) -> ModelCatalog:
    """Validate a catalog against its manifest and build the immutable snapshot."""
    try:
        manifest = json.loads(manifest_bytes.decode("utf-8"))
    except ValueError:
        raise CatalogError("invalid_manifest") from None
    if not isinstance(manifest, dict) or manifest.get("schema_version") != SCHEMA_VERSION:
        raise CatalogError("unsupported_manifest")
    pin, source = manifest.get("catalog"), manifest.get("source")
    if not isinstance(pin, dict) or not isinstance(source, dict):
        raise CatalogError("invalid_manifest")
    if (
        pin.get("bytes") != len(catalog_bytes)
        or pin.get("sha256") != hashlib.sha256(catalog_bytes).hexdigest()
    ):
        raise CatalogError("digest_mismatch")

    try:
        document = json.loads(catalog_bytes.decode("utf-8"))
    except ValueError:
        raise CatalogError("invalid_json") from None
    if not isinstance(document, dict) or document.get("schema_version") != SCHEMA_VERSION:
        raise CatalogError("unsupported_schema")
    version = document.get("litellm_version")
    if not isinstance(version, str) or version != source.get("version"):
        raise CatalogError("manifest_mismatch")
    raw_models, raw_unresolvable = document.get("models"), document.get("unresolvable")
    if not isinstance(raw_models, dict) or not raw_models or not isinstance(raw_unresolvable, list):
        raise CatalogError("invalid_structure")

    models: dict[str, Mapping[str, Any]] = {}
    for name, entry in raw_models.items():
        if not name or name in RESERVED_KEYS or not isinstance(entry, dict):
            raise CatalogError("invalid_entry")
        if not all(
            is_catalog_field(field) and is_valid_value(field, value)
            for field, value in entry.items()
        ):
            raise CatalogError("invalid_entry")
        models[name] = MappingProxyType(dict(entry))
    if not all(isinstance(name, str) and name in models for name in raw_unresolvable) or (
        raw_unresolvable != sorted(set(raw_unresolvable))
    ):
        raise CatalogError("invalid_structure")

    return ModelCatalog(
        models=MappingProxyType(models),
        public_models=frozenset(models),
        unresolvable=frozenset(raw_unresolvable),
        litellm_version=version,
    )


def _read_bounded(path: Path, limit: int) -> bytes:
    try:
        with path.open("rb") as handle:
            data = handle.read(limit + 1)
    except OSError:
        raise CatalogError("missing") from None
    if len(data) > limit:
        raise CatalogError("oversized")
    return data


_lock = threading.Lock()
_snapshot: ModelCatalog | None = None
_attempted = False


def load_model_catalog() -> ModelCatalog | None:
    """Return the validated pinned catalog, or ``None`` when it is unavailable.

    Loads at most once per process; concurrent first callers wait for one
    complete result. Unavailability is logged once with a fixed reason and is
    final for the process. Callers apply their own documented fallbacks. This
    never imports LiteLLM, reads user configuration or fetches replacement data.
    """
    global _snapshot, _attempted
    if _attempted:
        return _snapshot
    with _lock:
        if not _attempted:
            try:
                _snapshot = parse_catalog(
                    _read_bounded(DATA_DIR / CATALOG_FILE, MAX_CATALOG_BYTES),
                    _read_bounded(DATA_DIR / MANIFEST_FILE, MAX_MANIFEST_BYTES),
                )
            except CatalogError as exc:
                _log_unavailable(str(exc))
            except Exception:
                _log_unavailable("unreadable")
            _attempted = True
    return _snapshot


def _log_unavailable(reason: str) -> None:
    logger.warning(
        "Pinned model catalog unavailable (%s): savings use fallback estimates "
        "and telemetry omits model ids",
        reason,
    )
